# Generated by Django 4.0.6 on 2022-07-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='habit',
            name='metric',
            field=models.CharField(max_length=255),
        ),
    ]
