# Generated by Django 4.0.6 on 2022-07-15 11:20

from django.db import migrations, models
import habits.models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_date_date_alter_habit_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(default=None, validators=[habits.models.validate_date]),
        ),
    ]
