# Generated by Django 4.0.6 on 2022-07-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_remove_date_unique_user_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='habit_status',
            field=models.PositiveIntegerField(),
        ),
    ]
