# Generated by Django 4.0.6 on 2022-07-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_date_habit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='tracked_habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='habits.habit'),
        ),
    ]
